# Generated by Django 5.0.8 on 2024-08-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='courselink',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
