# Generated by Django 5.0.8 on 2024-08-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
